### PR TITLE
Fixed: (AnimeBytes) Add search by year for movies

### LINKED ISSUE #1564: Support year in query for AnimeBytes indexder
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

AnimeBytes (AB) has a category for movies. If I search for a movie via Radarr, the query URL for AB doesn't contain the year:
image

From my quick checking, the problem is that AB doesn't support years in `&searchstr` (so `Hero 2002` is passed as `&searchstr=Hero` - see the red text in the screenshot). I guess that's why it was omitted. However, it does support passing the year via `&year=YYYY` query param, like so: `https://animebytes.tv/scrape.php?username=m3Lith&torrent_pass=***&type=anime&searchstr=Hero&year=2018&anime[movie]=1`

### Describe the solution you'd like

Add support for passing a year via `&year` query param for AnineBytes indexder.

### Describe alternatives you've considered

.

### Anything else?

.

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Database Migration
NO

#### Issues Fixed or Closed by this PR

* Fixes #1564

### CODE REVIEW

**Comment by m3Lith** [comment]
The year still doesn't seem to be included in the queried url.

**Comment by m3Lith** [comment]
Tried it, still the same.

**Comment by m3Lith** [comment]
Where can I find `Search By Year` option?

**Comment by m3Lith** [comment]
In Prowlarr, there is no such setting for this indexer. In Radarr, the closest option is "Remove year from search string", but this has no effect.

**Comment by m3Lith** [comment]
Can confirm the latest image has the setting visible in the UI, and it works as expected.

**Review by Qstick — APPROVED** [review]

**Pull request merged**
