### PR TITLE
Fixed: (MaM) Handle Auth Errors & Session Expiry

### PR DESCRIPTION
**Pull request by bakerboy448**
#### Database Migration
NO

#### Description
see commit msg

#### Todos
- Tests
- Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by Qstick** [comment]
Tested?

**Comment by bakerboy448** [comment]
> Tested?

Not recently; but previous (and cleared :/) logs from an expired cookie (30 days) have MaM returning forbidden - confirmed scenario per old discord development message

**Comment by bakerboy448** [comment]
image
image

works

**Comment by bakerboy448** [comment]
image
image


works

**Review by Qstick — APPROVED** [review]

**Pull request merged**
