### PR TITLE
Fixed: (Cardigann) Add support for Cardigann path for attribute (UNIT3D)

### PR DESCRIPTION
**Pull request by DevYukine**
#### Database Migration
NO

#### Description
This fixes a bug which was introduced with a breaking change of definitions here https://github.com/Prowlarr/Indexers/commit/6c2070d49de474c542ef31c9108151f1302a23ce the Cardigann Parser wasn't updated for, this adds non breaking support for this new place of Attribute

#### Todos
- [x] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

Issue was mentioned to me in Discord
* Closes https://github.com/Prowlarr/Prowlarr/pull/851

### CODE REVIEW

**Comment by bakerboy448** [comment]
@Qstick v5? Or will this be moot then since we're rewriting everything.

Unless we keep this as v4 and then also push out a dev with it?

**Comment by Qstick** [comment]
Make it v5, we'll bump the other

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
Bump Cardigann def to v5

**Comment by Qstick** [comment]
Can you PR the indexers to v5 and update the script? I think they (all with attribute change) were all reverted from v4

**Pull request closed without merging**
