### PR TITLE
Fixed: MoreThanTV indexer from browse page layout changes (#788, #922)

### LINKED ISSUE #788: MTV is miscalculating sizes resulting in items being declined
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

while searching for a particular season it appears my preferred choice of torrent was being refused due to surpassing the size limit.  Upon further inspection it seems that the results being returned for that item are for ALL torrents of that show/season on MTV.

easier to explain with pictures. 

exhibit A) the torrent I want from MTV in the search results of sonarr
image

exhibit B) the same torrent on MTV's website
image

exhibit C) all other torrents for that show/season on the website which cumulatively make up the GB size being returned in the search resulting in it being ginormous and refused
image

### Expected Behavior

for a proper file size to be returned so (in this case) the file(s) are not removed from consideration if nothing else. 

### Steps To Reproduce

add the mtv indexer to prowlarr and proceed to add The Originals (2013) as a series.
perform an interactive search for season 4 and note the size of the "The.Originals.S04.720p.HDTV.DD5.1x264-BTN" torrent shown  here https://www.morethantv.me/torrents.php?id=248058#torrentinfo217727

i can only assume this will present with other shows/seasons as well. 

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.2.0.1395
- Docker Install:
- Using Reverse Proxy:
- Browser: Brave
```

### What branch are you running?

Nightly

### Trace Logs?

prowlarr

https://0bin.net/paste/8s7xpPus#VnLETgh9BSTHT+P5yRJv0lZzMflmVQajeLPZC+VW-0u

sonarr
[sonarr.trace.1.txt](https://github.com/Prowlarr/Prowlarr/files/7885742/sonarr.trace.1.txt)
[sonarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7885743/sonarr.trace.txt)
[sonarr.trace.0.txt](https://github.com/Prowlarr/Prowlarr/files/7885744/sonarr.trace.0.txt)

[AB#2399](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2399)

### LINKED ISSUE #922: Mtv responds with a html page instead of the torrent
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My trace log
[https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB](https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB)

and here one posted by vityav in discord as well

[https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB](https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB)

Prowlarr says the searches are failing, but the link it shows results just fine.
The trace logs show it's pulling down the entire html of the page with all the torrents, 
The generic error seems to be: "Unexpected Response content"

In my understanding this GHI can be assigned to Yukine

### Expected Behavior

Have a working search/hit as per normal functionality like with other trackers.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: Version 0.2.0.1632
            Package Version nightly-3873014 by hotio 
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

Tracelogs:

[https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB](https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB)

[https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB](https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB)

[AB#2893](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2893)

### PR DESCRIPTION
**Pull request by missingfile**
#### Database Migration
NO

#### Description
Updates MoreThanTV's browse endpoint and fixes HTML query selectors.

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #922 
* Fixes #788

### CODE REVIEW

**Comment by bakerboy448** [comment]
@missingfile, tested?
@DevYukine seem sane to you?

**Comment by DevYukine** [comment]
Seems fine to me, MTV recently changed away from the weird group layout and this finally fixes #788 🎉

**Comment by missingfile** [comment]
@bakerboy448 Working on it. Is there a TLDR for Linux building and running? I ran build.sh, but do not know how to start this thing up.

**Review by Qstick — APPROVED** [review]

**Comment by Qstick** [comment]
@missingfile 

Linux x64 build artifact is here if you want to run it
https://artprodcus3.artifacts.visualstudio.com/Addc1cc14-cc9f-4ffc-9582-14210bdf4c91/a958e221-aeac-4b0e-a862-d8ffe1df4b09/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL1Byb3dsYXJyL3Byb2plY3RJZC9hOTU4ZTIyMS1hZWFjLTRiMGUtYTg2Mi1kOGZmZTFkZjRiMDkvYnVpbGRJZC8xNjY1L2FydGlmYWN0TmFtZS9QYWNrYWdlcw2/content?format=file&subPath=%2FProwlarr.merge.0.2.0.1636.linux-core-x64.tar.gz

**Pull request merged**
