### PR TITLE
Fixed: (Avistaz) Cleanse PID & Hash from response

### LINKED ISSUE #557: [BUG]: keys and PIDs not cleansed for Avistaz
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
2021-10-23T15:10:22.238849352Z RequestUri: https://avistaz.to/api/v1/jackett/torrents?in=1&type=1&search=;StatusCode: OK;ContentType: application/json;ContentLength: 94326;ContentSample: {"current_page":1,"data":[{"id":185306,"url":"https:\/\/avistaz.to\/torrent\/185306-womens-house-1954-720p-web-dl-amzn-vz","download":"https:\/\/avistaz.to\/rss\/download\/xxxxxxxxxxxxxxxxxxxxxxxxx\/010101010101010101010101101010010101010101010010.torrent","type_id":1,"type":"Movie","info_hash":"00000000000000000000000000000000000000000","file_name":"Women's House 1954 720p WEB-DL AMZN VZ","file_size":742363715,"file_count":1,"seed":1,"leech":1,"completed":0,"downloaded":5,"upload_multiply":1,"download_multiply":1,"adult":false,"video_quality_id":2,"video_quality":"720p","rip_type_id":12,"rip_type":"WEB-DL","movie_tv":{"imdb":"tt2513698","tmdb":"868810","tvdb":null,"title":"Women's House","tv_season":null,"tv_episode":null,"tv_full_season":false,"tv_complete":false},"audio":[{"id":79,"language":"Japanese"}],"subtitle":null,"music_type":null,"created_at":"2021-10-23 10:45:11"},{"id":185298,"url":"https:\/\/avistaz.to\/torrent\/185298-love-letter-1981-1080i-bluray-raw-avc-truehd20-d1k","download":"https:\/\/avistaz.to\/rss\/download\/xxxxxxxxxxxxxxxxxxxxxxxxx\/010101010101010101010101101010010101010101010010.torrent","type_id":1,"type":"Movie","info_hash":"00000000000000000000000000000000000000000","file_name":"Love Letter 1981 1080i BluRay Raw AVC TrueHD2.0-d1k","file_size":22311913083,"file_count":178,"seed":16,"leech":2,"completed":19,"downloaded":37,"upload_multiply":1,"download_multiply":0,"adult":true,"video_quality_id":7,"video_quality":"1080i","rip_type_id":15,"rip_type":"BluRay Raw","movie_tv":{"imdb":"tt0082683","tmdb":"584687","tvdb":null,"title":"Love Letter","tv_season":null,"tv_episode":null,"tv_full_season":false,"tv_complete":false},"audio":[{"id":79,"language":"Japanese"}],"subtitle":[{"id":79,"language":"Japanese"}],"music_type":null,"created_at":"2021-10-23 08:31:29"},{"id":185295,"url":"https:\/\/avistaz.to\/torrent\/185295-horror-of-the-wolf-1973-480i-dvd-mpeg-dd20","download":"https:\/\/avistaz.to\/rss\/download\/xxxxxxxxxxxxxxxxxxxxxxxxx\/010101010101010101010101101010010101010101010010.torrent","type_id":1,"type":"Movie","info_hash":"00000000000000000000000000000000000000000","file_name":"Horror of the Wolf 1973 480i DVD MPEG DD2.0","file_size":4390346752,"file_count":26,"seed":1,"leech":8,"completed":0,"downloaded":23,"upload_multiply":1,"download_multiply":1,"adult":false,"video_quality_id":1,"video_quality":"SD","rip_type_id":4,"rip_type":"DVD","movie_tv":{"imdb":"tt0070962","tmdb":"342088","tvdb":null,"title":"Horror of the Wolf","tv_season":null,"tv_episode":null,"tv_full_season":false,"tv_complete":false},"audio":[{"id":79,"language":"Japanese"}],"subtitle":[{"id":45,"language":"English"}],"music_type":null,"created_at":"2021-10-23 08:03:56"},{"id":185285,"url":"https:\/\/avistaz.to\/torrent\/185285-please-her-2020-1080p-nf-web-dl-ddp51-x264-taengoo","download":"https:\/\/avistaz.to\/rss\/download\/xxxxxxxxxxxxxxxxxxxxxxxxx\/010101010101010101010101101010010101010101010010.torrent","type_id":1,"type":"Movie","info_hash":"00000000000000000000000000000000000000000","file_name":"Please (Her) 2020 1080p NF WEB-DL DDP5.1 x264-Taengoo","file_size":3904035076,"file_count":1,"seed":10,"leech":0,"completed":13,"downloaded":26,"upload_multiply":1,"download_multiply":1,"adult":false,"video_quality_id":3,"video_quality":"1080p","rip_type_id":12,"rip_type":"WEB-DL","movie_tv":{"imdb":null,"tmdb":"779273","tvdb":null,"title":"Begging (You)","tv_season":null,"tv_episode":null,"tv_full_season":false,"tv_complete":false},"audio":[{"id":162,"language":"Thai"}],"subtitle":[{"id":45,"language":"English"},{"id":162,"language":"Thai"}],"music_type":null,"created_at":"2021-10-23 04:28:32"}
```

### Expected Behavior

Logs are cleansed

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: agnostic
- Prowlarr: v0.1.1.978
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Develop

### Anything else?

Ref https://github.com/Prowlarr/Prowlarr/issues/556

[AB#1799](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1799)

### PR DESCRIPTION
**Pull request by bakerboy448**
Fixes #557

#### Database Migration
NO

#### Description
title
#### Todos
- [x] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by eckozen84** [comment]
@bakerboy448 have tested with the new hotio build and still seeing the same error. Now it happens on both sonarr and radarr upon addition into prowlarr. Have attached full log below.

[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7403887/prowlarr.txt)

**Comment by bakerboy448** [comment]
> @bakerboy448 have tested with the new hotio build and still seeing the same error. Now it happens on both sonarr and radarr upon addition into prowlarr. Have attached full log below.
> 
> [prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7403887/prowlarr.txt)

- also FYI container logs and info logs are useless for debugging
- container logs are ~console logs and are NOT cleansed

Were the PID and hashes cleansed in the actual trace log file?

**Comment by eckozen84** [comment]
I misunderstood, I get what you are trying to do now. Not to familiar with trace logging, how do i check that?

**Comment by bakerboy448** [comment]
> I misunderstood, I get what you are trying to do now. Not to familiar with trace logging, how do i check that?

it'd be the same logs / testing as the main github issue you reported and manually cleansed; in theory the PID and Hash should be cleansed and replaced with `(removed)`

**Comment by bakerboy448** [comment]
> The main github issue log that I posted was still just container log. If you could show me how to check the trace log I would be happy to confirm if it's correctly cleansed.

If that was the container log then there may have been nothing to cleanse and this PR may not even be needed.....

The github bug issue template explicitly calls this out.

> Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)
Links? References? Anything that will give us more context about the issue you are encountering!
Generally speaking, all bug reports must have trace logs provided.

How can the template be improved as it seems this section is almost always ignored and never read by users?

**Comment by bakerboy448** [comment]
Cleansed in this PR or cleansed in develop/nightly

**Comment by eckozen84** [comment]
It was cleansed in this PR. The develop still shows the PID and torrent hashes.

**Pull request merged**
