### PR TITLE
Fixed: (LazyLibrarian) Sync priority

### LINKED ISSUE #1304: LazyLibrarian indexer priorities
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Prowlarr can synch indexers with LazyLibrarian, but when it does so on the LL end, all the priorities are 0, instead of what they're set to on Prowlarr. 

### Describe the solution you'd like

Apply prowlarr priorities to indexers imported into LL

### Describe alternatives you've considered

None

### Anything else?

Screenshot_20230108-095627
Screenshot_20230108-095742

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Database Migration
NO

#### Description
Sync indexer priority with LazyLibrarian

* Fixes #1304

### CODE REVIEW

**Comment by Qstick** [comment]
I'm not familiar with LL data model, but do our `int` priorities and their order align with LL? Just want to make sure passing it straight makes sense.

**Comment by Qstick** [comment]
Hard to tell from their docs, highest priority could really mean largest or smallest number.  https://lazylibrarian.gitlab.io/config_providers/#priorities

> download is available from more than one provider we request it from the one with the highest priority

vs Prowlarr

> Indexer Priority from 1 (Highest) to 50 (Lowest)

**Comment by Qstick** [comment]
Seems it might be opposite from us, highest number?

https://gitlab.com/LazyLibrarian/LazyLibrarian/-/blob/master/lazylibrarian/resultlist.py#L274-L278

**Comment by i-am-at0m** [comment]
I haven't tested the feature but my understanding is the same as yours

**Comment by i-am-at0m** [comment]
I'd be happy to do that if I knew how to get my docker to run your pr

**Review by Qstick — APPROVED** [review]

**Pull request merged**
