### PR TITLE
Fix: (M-Team) Unavailable issue

### LINKED ISSUE #1061: Can't add indexers m-team (mteam)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add indexer m-team always show "Unable to connect to indexer, check the log for more details"

### Expected Behavior

Indexer added successfully

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Synology DSM 7.1
- Prowlarr:0.4.2.1879
- Docker Install:Yes
- Using Reverse Proxy:No
- Browser:Chrome newest version
```

### What branch are you running?

develop

### Trace Logs?

https://pastebin.com/R321SeGg

### PR DESCRIPTION
**Pull request by luckyboy**
#### Database Migration
NO

#### Description
M-Team Indexer can't work properly

#### Todos
- [ ] Tests

#### Issues Fixed or Closed by this PR

* Fixes #1061

### CODE REVIEW

**Comment by bakerboy448** [comment]
Again, Cardigann changes that are not backwards compatible require a Cardigann version bump

**Comment by bakerboy448** [comment]
No an entire new Cardigann version would be needed as previously explained on your closed PRs.

**Comment by luckyboy** [comment]
> No an entire new Cardigann version would be needed as previously explained on your closed PRs.
Sorry, i'm not very clear about the Cardigann version control mechanism.
Is that means i need to add definition file to a new v8 folder and change DEFINITION_VERSION in  IndexerDefinitionUpdateService to 8?

**Comment by luckyboy** [comment]
> No an entire new Cardigann version would be needed as previously explained on your closed PRs.

  Sorry, i'm not very clear about the Cardigann version control mechanism.
  Is that means i need to add definition file to a new v8 folder and change DEFINITION_VERSION in  IndexerDefinitionUpdateService to 8?

**Comment by AbuRyu** [comment]
I have M-Team working fine, since the most recent dev version dropped.

**Comment by luckyboy** [comment]
> Yes and update the schema file for Cardigann v8

Got it, thank you.

**Pull request closed without merging**
