### PR TITLE
Anilibria: Fix download torrent link

### PR DESCRIPTION
**Pull request by dm3ch**
#### Database Migration
NO

#### Description
Fix redirect problem when downloading torrent files

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by Qstick** [comment]
Do you have an example of the issue here?

**Comment by dm3ch** [comment]
@Qstick I haven't found issue for that and didn't open it myself.

The problem is:
When you downloads torrent file it's broken. If you tries to download release from Prowlarr you gets:
```
Task Error: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Invalid torrent file specified)
 ---> MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
   --- End of inner exception stack trace ---
[Error] GlobalExceptionHandlers: Task Error

[v0.1.1.978] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
```

The reason of that problem is that current indexer code returns torrent file download URL that redirects to actual URL (and Prowlarr reports about that in developer mode), so this PR just changes URL composition logic to provide torrent file URL that wouldn't be redirected

**Comment by Qstick** [comment]
Sounds good, just wanted it explained here for the record

**Comment by gmcinalli** [comment]
Hi @dm3ch, I've re-checked and I confirm that I'm using the `0.1.1.1030` version.

@bakerboy448 Here's the [trace log](https://www.toptal.com/developers/hastebin/qihepibeji.pl) that should show the issue I'm getting.

The torrent file that I'm trying to download is listed also in the log, but I'm getting this problem with every torrent I try directly in Prowlarr.

**Comment by gmcinalli** [comment]
Also, these are the indexer settings I am trying to get to work.

image

I noticed that even setting the *Download link* to **magnet** downloads are successfully sent to Transmission.

**Comment by dm3ch** [comment]
@gmcinalli I looked into your logs and it seems this problem is not connected with Anilibria.

It seems that 1337x indexer just could have similar issue to what have been just fixed in Anilibria. So I would recommend you to open separate issue to discuss this problem

**Pull request merged**
