### PR TITLE
Amend indexer list info

### PR DESCRIPTION
**Pull request by Hawkinzzz**
Sentence used from https://wiki.servarr.com/prowlarr/indexers

#### Database Migration
NO

#### Description
To clarify what to use if your indexer is not in the list to new users without having to look in the documentation.

#### Todos
- [x] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com) (already exists)

### CODE REVIEW

**Review by bakerboy448 — APPROVED** [review]

**Comment by Qstick** [comment]
Why is this approved and on hold @bakerboy448

**Comment by bakerboy448** [comment]
> Why is this approved and on hold @bakerboy448


were discussing on discord to see what the optimal text is / any better wording suggestions.

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
I think
```
Prowlarr supports many indexers in addition to any indexer that uses the Newznab/Torznab standard using 'Generic Newznab' (for usenet) or 'Generic Torznab' (for torrents). Search & Select your indexer from below.
``` will be a bit cleaner

**Comment by Hawkinzzz** [comment]
Thanks for the suggestion @bakerboy448, I have updated as requested.

**Review by bakerboy448 — APPROVED** [review]

**Pull request merged**
