### PR TITLE
BroadcastheNet Query Limit Handling

### PR DESCRIPTION
**Pull request by bakerboy448**
#### Database Migration
NO

#### Description
- Prevent hitting BTN's rate limiting
- this may cause issues with searching though with such a high limit

#### Todos
- Tests
- Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes User Issues

### CODE REVIEW

**Comment by Qstick** [comment]
Ouch, yea that limit is quite high

**Comment by bakerboy448** [comment]
> Ouch, yea that limit is quite high

Yeah not great... 

alternatively it may be helpful if we catch the error?

```
2022-01-04 00:59:05.7|Warn|BroadcastheNet|http://api.broadcasthe.net/

[v0.1.10.1357] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned an error [{
  "code": -32002,
  "message": "Call Limit Exceeded"
}]
   at NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\BroadcastheNet\BroadcastheNetParser.cs:line 60
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
RequestUri: http://api.broadcasthe.net/;RequestSummary: getTorrents("(removed)", {"Search":"Scream%1996"}, 100, 0);StatusCode: OK;ContentType: application/json;ContentLength: 87;ContentSample: {"id":"f20b48b7","result":null,"error":{"code":-32002,"message":"Call Limit Exceeded"}}
```

**Comment by Qstick** [comment]
> > Ouch, yea that limit is quite high
> 
> Yeah not great... 
> 
> alternatively.... maybe helpful if we catch the error and then disable til the next hour?
> 
> pushed a commit for the catch
> 
> ```
> 2022-01-04 00:59:05.7|Warn|BroadcastheNet|http://api.broadcasthe.net/
> 
> [v0.1.10.1357] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned an error [{
>   "code": -32002,
>   "message": "Call Limit Exceeded"
> }]
>    at NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\BroadcastheNet\BroadcastheNetParser.cs:line 60
>    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
>    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
> RequestUri: http://api.broadcasthe.net/;RequestSummary: getTorrents("(removed)", {"Search":"Scream%1996"}, 100, 0);StatusCode: OK;ContentType: application/json;ContentLength: 87;ContentSample: {"id":"f20b48b7","result":null,"error":{"code":-32002,"message":"Call Limit Exceeded"}}
> ```

Good call

**Comment by bakerboy448** [comment]
gotta fix the error catching code

```
An error occurred while processing indexer feed. http://api.broadcasthe.net/: Cannot access child value on Newtonsoft.Json.Linq.JProperty.

System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\BroadcastheNet\BroadcastheNetParser.cs:line 53
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
```

**Pull request closed without merging**
