### PR TITLE
Removed suspicious URL in the default definitions

### PR DESCRIPTION
**Pull request by rumplin**
#### Database Migration
NO

#### Description
Removed suspicious URL from the code. Looks like the site that was originally there doesn't exist anymore and it's hosting malware (HD4Free.xyz).

#### Screenshot (if UI related)
none

#### Todos
- none

### CODE REVIEW

**Comment by bakerboy448** [comment]
this PR only updates git ignore? - those changes need to be reverted

**Comment by rumplin** [comment]
Please ignore this commit. Some error happened on my side.

**Comment by rumplin** [comment]
Should be fine now.

**Comment by bakerboy448** [comment]
squash the commits down to just the correct one please

**Pull request merged**
