### PR TITLE
New: (Rarbg) Add caching results

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Database Migration
NO

#### Description
https://discord.com/channels/264387956343570434/264388019585286144/1102185483557154938

### CODE REVIEW

**Comment by Qstick** [comment]
Baker mentioned he can't comment because of the block 

Do we really want a setting here? It's messy to put this in user hands. Could we reduce to 10, do a cache like AB and also only use the second rate limit for search and not RSS? 

Just a few options (from Baker on Discord)

**Comment by bakerboy448** [comment]
- The 429s I don't think are often triggered if they were then we could fix this prowlarr/jackett side
- the 520s we have no control over nor fix as it's their internal servers that are unable to handle the load.....unless we can control literally every single client hitting rarbg's servers which we can't :\

Suggest
- rss keep the 31s rate limit req but add a 30s ? cache like AB and similar to jackett; this should cut down on quite a few requests 
- keep normal searches at their existing limit

General comment: we're already doing exactly what rarbg asks; if their servers cannot handle their normal traffic load, that's on them

**Comment by bakerboy448** [comment]
rebase ;)

**Review by bakerboy448 — APPROVED** [review]

**Review by Qstick — APPROVED** [review]
Let's give it a go

**Pull request merged**
